# ---------------------
# CONFIGURATION
# ---------------------
import os

# Input data directory
DATA_DIR = "data"
# Output directories
PARSED_DIR = "parsed"
BOLTZ_DIR = "../boltz_results"
PLOTS_DIR = "../plots"

# Ensure output directories exist
for d in [PARSED_DIR, BOLTZ_DIR, PLOTS_DIR]:
    os.makedirs(d, exist_ok=True)

# List all input files
SAMPLES = glob_wildcards(os.path.join(DATA_DIR, "{sample}.txt")).sample

# -------------------
# RULES
# -------------------

rule all:
    """
    The final target rule that defines workflow outputs.
    """
    input: expand(os.path.join(PLOTS_DIR, "{sample}.png"), sample=SAMPLES)

# --------------------
# Download proteome
# --------------------

# ----------------------------------
# Parse proteome into .yaml files
# ----------------------------------
rule parse_data:
    input:
        raw=os.path.join(DATA_DIR, "{sample}.txt")
    output: 
        parsed=os.path.join(PARSED_DIR, "{sample}_parsed.txt")
    shell:
        """
        # Replace with parsing command
        python scripts/parse_data.py {input.raw} > {output.parsed}
        
        """

# ----------------------------------
# Generate proteome chunks for MSA
# ----------------------------------

# --------------------------------
# Generate MSA for each protein
# --------------------------------


# ---------------------------------------
# Run boltz on parsed data with MSAs
# ---------------------------------------
rule run_boltz:
    input:
        parsed=os.path.join(PARSED_DIR, "{sample}_parsed.txt")
    output:

# ------------------
# Parse output
# ------------------

# ------------------
# Generate plots 
# ------------------
