import glob
import csv
import os

configfile: "config/config.yaml"

FASTA_DIR = config["dirs"]["fasta"]
MSA_DIR = config["dirs"]["msa"]
YAML_DIR = config["dirs"]["yaml"]
INPUT_DIR = config["dirs"]["input"]
BOLTZ_DIR = config["dirs"]["boltz"]
PREDICTIONS_DIR = os.path.join(BOLTZ_DIR, "predictions")


LIGANDS = f"{INPUT_DIR}/ligands/cancer_ligands.csv"
LIGAND_INFO = {}
with open(LIGANDS) as f:
    reader = csv.DictReader(f)
    for row in reader:
        LIGAND_INFO[row["ligand_id"]] = row

LIGAND_IDS = list(LIGAND_INFO.keys())
PROTEINS = [Path(f).stem for f in glob.glob(os.path.join(FASTA_DIR, "*.fasta"))]

print(f"Loaded {len(PROTEINS)} proteins")
print(f"Loaded {len(LIGAND_IDS)} ligands")


rule all:
    input:
        expand(
            os.path.join(PREDICTIONS_DIR, "{protein}_{ligand}"),
            protein=PROTEINS,
            ligand=LIGAND_IDS
        )

rule generate_yaml:
    input:
        fasta=f"{FASTA_DIR}/{{protein}}.fasta",
        msa=lambda wc: f"{MSA_DIR}/{wc.protein}/msa.a3m" if os.path.exists(f"{MSA_DIR}/{wc.protein}/msa.a3m") else [],
    output:
        yaml=f"{YAML_DIR}/{{protein}}_{{ligand}}.yaml"
    log:
        f"logs/generate_yaml/{{protein}}_{{ligand}}.log"
    params:
        ligand_type=lambda wc: LIGAND_INFO[wc.ligand]["type"],
        ligand_value=lambda wc: LIGAND_INFO[wc.ligand]["value"]
    threads: 1
    resources:
        mem_mb=1000,
        runtime=10
    shell:
        r"""
        set -euo pipefail

        msa_arg=""
        if [[ -f {input.msa} ]]; then
            msa_arg="--msa_file {input.msa}"
        fi
        
        python generate_yaml.py \
            --fasta_file {input.fasta} \
            $msa_arg \
            --ligand_id {wildcards.ligand} \
            --ligand_type "{params.ligand_type}" \
            --ligand_value "{params.ligand_value}" \
            --output_yaml {output.yaml} \
            > {log} 2>&1
        """

rule run_boltz:
    input:
        yaml=f"{YAML_DIR}/{{protein}}_{{ligand}}.yaml"
    output:
        directory(os.path.join(PREDICTIONS_DIR, "{protein}_{ligand}"))
    log:
        f"logs/run_boltz_batch/{{protein}}_{{ligand}}.log"
    threads: 4
    resources:
        mem_mb=32000,
        runtime=60,
        gpu=1,
        slurm_partition="rai-gpu-grn",
        slurm_account="rai",
        slurm_qos="rai-gpu-grn"
        slurm_extra="--gres=gpu:h200:1"
    shell:
        r"""
        set -euo pipefail

        scripts/run_boltz.sh \
            {input.yaml} \
            {output} \
            {threads} \
            > {log} 2>&1
        """